/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.bigblues.jpa.sample;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
